### ISSUE TITLE
MySQL Bağımlılığı

### ISSUE THREAD

**Issue by hyperpostulate** [sefaerkan/Java-RestAPI#1]
Merhaba Sefa,
Projeyi inceledim. Öncelikle eline sağlık.

Projede MySQL bağımlılığı olduğu için, localindeki MySQL'de yaptığın işlemleri de açıklayıcı bir döküman hazırlamak faydalı olacaktır.

Kök dizinde **SETUP.md** isminde bir markdown dökümanı oluşturup o döküman üzerinde İngilizce olarak açıklamanı isteyeceğim.

Bu döküman içeriğinde projenin çalışması için ilgili sunucuda ya da localde MySQL'in hangi sürümünün nasıl kurulacağı, kurulan sürüm üzerindeki instance'ta User tablosunun nasıl create edileceğine dair create scripti, ve application.properties'de belirttiğin datasource URL'inin nasıl değiştirilmesi gerektiği yer almalı.

Kurulum işlemlerini uzadı uzadıya yazman gerekmiyor, official dökümantasyonun linkini paylaşabilirsin. Markdown formatı hyperlink'lere izin veriyor.

Create scriptini ise resources dizini içerisine koyabilirsin.

Kod kalitesine ve yeni feature isteklerine dair ayrı issue'lar açacağım.

Kolaylıklar,
Mesut ORMANLI

**Comment by hyperpostulate** [comment]
Öneri: bu sayfada sağ tarafta "Development" bölümü mevcut. Oradan "Create a branch"e tıklayıp feature/documentation isminde bir branch oluşturabilirsin.

**Comment by sefaerkan** [comment]
Tamamlandı.
