### ISSUE TITLE
feature/dockerize

### ISSUE THREAD

**Issue by hyperpostulate** [sefaerkan/Java-RestAPI#3]
Sefa merhaba,
Geliştirdiğimiz uygulamaları dockerize ederek bir docker container'ı üzerinde çalıştırmak, hem modern bir yaklaşım, hem de birçok artısı var: örneğin klasik "localimde çalışıyor" (it works on my machine) sorununu çözmek gibi.

Bu feature kapsamında, docker'ı araştırmanı, local'ine kurmanı, ve bu uygulamayı dockerize ederek docker üzerinde çalıştırmanı isteyeceğim.

Uygulaman merkezi bir RDBMS (MySQL) kullandığı için, veritabanı bağlantısını dockerize etmek kolay değil. Dolayısıyla o kısmı şimdilik atlıyoruz. Sadece uygulamayı dockerize etmen yeterli olacak.

Faydalı olacağını düşündüğüm linkleri aşağıda paylaşıyorum:

https://www.yusufsezer.com.tr/docker/

https://metinalniacik.medium.com/spring-boot-uygulamas%C4%B1n%C4%B1-docker-konteyner%C4%B1-haline-getirmek-bcf22a2f6d7

Not: linklerdeki açıklamalar eski ve/veya kullandığın sürümle uyumsuz olabilir. Bu durumda biraz araştırma yapman gerekecek.

Kolaylıklar,
Mesut ORMANLI

**Comment by sefaerkan** [comment]
yapıldı
