### ISSUE TITLE
feature/github_actions

### ISSUE THREAD

**Issue by hyperpostulate** [sefaerkan/Java-RestAPI#4]
Sefa selamlar,
Geliştirdiğimiz projelerde, CI / CD süreçlerini entegre etmek projelerin sürdürülebilirliği açısından önemli katkılar sağlıyor.

CI / CD süreçlerine dair temel oluşturabilecek bir kaynak: https://caylakyazilimci.com/post/ci-cd-nedir

CI / CD süreçleri genellikle maliyetli yapılar gerektirmesine rağmen, GitHub platformunda geliştirilen projelerde en azından CI tarafında kullanabileceğimiz çeşitli araçlar mevcut. Bu araçlardan en pratik olanı Github Actions.

Bu issue kapsamında, Github Actions üzerinden kullanılabilecek "Java with Maven" action'ını projeye entegre etmeni isteyeceğim.

Bu action ile beraber, repository'deki master branchine pushlanan her commit sonrasında projenin maven ile build edilmesi ve build'in fail olması durumunda farkındalık oluşması sağlanacak.

Kolaylıklar,
Mesut ORMANLI

**Comment by sefaerkan** [comment]
"Java with Maven" action'ı projeye entegre edilmiştir.

![java](https://github.com/sefaerkan/Java-RestAPI/assets/36763407/5b46d6c9-1313-46f1-95cc-05cdc5aaa007)
